name: FARAO iTools Docker Image CI

on:
  push:
    branches: [ master ]
    paths: [ farao-itools ]
  pull_request:
    branches: [ master ]
    paths: [ farao-itools ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build farao-itools --tag farao/itools:$(date +%s)
